export function getRefundPayload(invoiceNumber, invoiceValue, orderId) {
  return {
    invoiceNumber,
    invoiceValue,
    issuanceDate: new Date(),
    type: 'Input',
    items: [
      {
        uniqueId: 'A7030227121F412E9EDF2ACECB89A62B',
        id: '880260',
        productId: '880026',
        ean: null,
        lockId: `00-${orderId}`,
        itemAttachment: {
          content: {},
          name: null,
        },
        attachments: [],
        quantity: 2,
        seller: '1',
        name: 'Yellow Onions (10 lbs.)',
        refId: '880260a',
        price: 5000,
        listPrice: 5000,
        manualPrice: null,
        priceTags: [
          {
            name: 'TAXHUB@CA STATE TAX',
            value: 600,
            isPercentual: false,
            identifier: null,
            rawValue: 6,
            rate: null,
            jurisCode: null,
            jurisType: null,
            jurisName: null,
          },
          {
            name: 'TAXHUB@CA STATE TAX (SHIPPING)',
            value: 29,
            isPercentual: false,
            identifier: null,
            rawValue: 0.29,
            rate: null,
            jurisCode: null,
            jurisType: null,
            jurisName: null,
          },
          {
            name: 'TAXHUB@CA COUNTY TAX',
            value: 25,
            isPercentual: false,
            identifier: null,
            rawValue: 0.25,
            rate: null,
            jurisCode: null,
            jurisType: null,
            jurisName: null,
          },
          {
            name: 'TAXHUB@CA COUNTY TAX (SHIPPING)',
            value: 1,
            isPercentual: false,
            identifier: null,
            rawValue: 0.01,
            rate: null,
            jurisCode: null,
            jurisType: null,
            jurisName: null,
          },
          {
            name: 'TAXHUB@CA SPECIAL TAX',
            value: 325,
            isPercentual: false,
            identifier: null,
            rawValue: 3.25,
            rate: null,
            jurisCode: null,
            jurisType: null,
            jurisName: null,
          },
          {
            name: 'TAXHUB@CA SPECIAL TAX (SHIPPING)',
            value: 17,
            isPercentual: false,
            identifier: null,
            rawValue: 0.17,
            rate: null,
            jurisCode: null,
            jurisType: null,
            jurisName: null,
          },
        ],
        imageUrl:
          'https://productusqa.vteximg.com.br/arquivos/ids/155713-55-55/yellow-onions.jpg?v=637745847018530000',
        detailUrl: '/yellow-onions/p',
        components: [],
        bundleItems: [],
        params: [],
        offerings: [],
        sellerSku: '880260',
        priceValidUntil: null,
        commission: 0,
        tax: 0,
        preSaleDate: null,
        additionalInfo: {
          brandName: 'Brand',
          brandId: '9280',
          categoriesIds: '/9282/',
          categories: [
            {
              id: 9282,
              name: 'Food and beverage',
            },
          ],
          productClusterId: '139,141,145,146,147,148',
          commercialConditionId: '1',
          dimension: {
            cubicweight: 0.2083,
            height: 10,
            length: 10,
            weight: 10,
            width: 10,
          },
          offeringInfo: null,
          offeringType: null,
          offeringTypeId: null,
        },
        measurementUnit: 'un',
        unitMultiplier: 1,
        sellingPrice: 5000,
        isGift: false,
        shippingPrice: null,
        rewardValue: 0,
        freightCommission: 0,
        priceDefinition: {
          sellingPrices: [
            {
              value: 5000,
              quantity: 2,
            },
          ],
          calculatedSellingPrice: 5000,
          total: 10000,
        },
        taxCode: '',
        parentItemIndex: null,
        parentAssemblyBinding: null,
        callCenterOperator: null,
        serialNumbers: null,
        assemblies: [],
        costPrice: 5000,
        index: 0,
        taxHubTotal: 9.97,
        warehouseId: '1_1',
        hasManualPrice: false,
        originalSellingPrice: 5000,
        selectableQuantity: [1, 2],
        selectedQuantity: 2,
        isSelected: true,
      },
    ],
  }
}
