export function getRefundPayload(invoiceNumber, invoiceValue, orderId) {
  return {
    invoiceNumber,
    invoiceValue,
    issuanceDate: new Date(),
    type: 'Input',
    items: [
      {
        uniqueId: '6AF3A37A7C7E4210B9ADFDB5393CC4D0',
        id: '2',
        productId: '1',
        ean: '1233333',
        lockId: `00-${orderId}`,
        itemAttachment: {
          content: {},
          name: null,
        },
        attachments: [],
        quantity: 2,
        seller: '1',
        name: 'Really Really Nice Hat Blue',
        refId: null,
        price: 4000,
        listPrice: 10000,
        manualPrice: null,
        priceTags: [
          {
            name: 'TAXHUB@FL STATE TAX',
            value: 480,
            isPercentual: false,
            identifier: null,
            rawValue: 4.8,
            rate: null,
            jurisCode: null,
            jurisType: null,
            jurisName: null,
          },
          {
            name: 'TAXHUB@FL STATE TAX (SHIPPING)',
            value: 76,
            isPercentual: false,
            identifier: null,
            rawValue: 0.76,
            rate: null,
            jurisCode: null,
            jurisType: null,
            jurisName: null,
          },
          {
            name: 'TAXHUB@FL COUNTY TAX',
            value: 80,
            isPercentual: false,
            identifier: null,
            rawValue: 0.8,
            rate: null,
            jurisCode: null,
            jurisType: null,
            jurisName: null,
          },
          {
            name: 'TAXHUB@FL COUNTY TAX (SHIPPING)',
            value: 29,
            isPercentual: false,
            identifier: null,
            rawValue: 0.29,
            rate: null,
            jurisCode: null,
            jurisType: null,
            jurisName: null,
          },
        ],
        imageUrl:
          'https://sandboxusdev.vteximg.com.br/arquivos/ids/189157-55-55/Sorting_Hat.png?v=637659458235430000',
        detailUrl:
          '/invicta-pro-diver-swiss-movement-quartz-watch---stainless-steel-case---model-0003/p',
        components: [],
        bundleItems: [],
        params: [],
        offerings: [],
        sellerSku: '2',
        priceValidUntil: null,
        commission: 0,
        tax: 0,
        preSaleDate: null,
        additionalInfo: {
          brandName: 'Invicta',
          brandId: '2000001',
          categoriesIds: '/1001/',
          categories: [
            {
              id: 1001,
              name: 'Watches',
            },
          ],
          productClusterId: '',
          commercialConditionId: '1',
          dimension: {
            cubicweight: 1,
            height: 1,
            length: 1,
            weight: 1,
            width: 1,
          },
          offeringInfo: null,
          offeringType: null,
          offeringTypeId: null,
        },
        measurementUnit: 'un',
        unitMultiplier: 1,
        sellingPrice: 4000,
        isGift: false,
        shippingPrice: null,
        rewardValue: 0,
        freightCommission: 0,
        priceDefinition: {
          sellingPrices: [
            {
              value: 4000,
              quantity: 2,
            },
          ],
          calculatedSellingPrice: 4000,
          total: 8000,
        },
        taxCode: 'PC040210',
        parentItemIndex: null,
        parentAssemblyBinding: null,
        callCenterOperator: null,
        serialNumbers: null,
        assemblies: [],
        costPrice: 5000,
        index: 0,
        taxHubTotal: 6.6499999999999995,
        warehouseId: 'S0017-L0017',
        hasManualPrice: false,
        originalSellingPrice: 4000,
        selectableQuantity: [1, 2],
        selectedQuantity: 2,
        isSelected: true,
      },
    ],
  }
}
