import { PRODUCTS } from './sandbox_products.js'

export default {
  singleProduct: {
    prefix: 'singleProduct',
    postalCode: '33180',
    totalAmount: '$ 101.65',
    tax: '$ 6.65',
    productPrice: '40.00',
    subTotal: '$ 80.00',
    // singleProduct, taxExemption, vatNumber,multiProduct,refund,externalSeller uses below product
    productName: PRODUCTS.hat,
    productQuantity: '2',
  },
  multiProduct: {
    prefix: 'multiProduct',
    postalCode: '33180',
    pickUpPostalCode: '33180',
    totalAmount: '$ 173.86',
    tax: '$ 11.37',
    subTotal: '$ 154.99',
    product1Name: PRODUCTS.hat,
    product2Name: PRODUCTS.testproduct3,
    productQuantity: '2',
    product1Price: '40.00',
    product2Price: '74.99',
  },
  discountProduct: {
    prefix: 'discountProduct',
    postalCode: '33180',
    totalAmount: '$ 88.26',
    tax: '$ 5.77',
    subTotal: '$ 74.99',
    productQuantity: '1',
    productPrice: '74.99',
    productName: PRODUCTS.testproduct3,
    env: 'discountProductEnv',
  },

  discountShipping: {
    prefix: 'discountShipping',
    postalCode: '14589',
    totalAmount: '$ 58.36',
    tax: '$ 3.82',
    discount: '$ -19.77',
    subTotal: '$ 59.31',
    productQuantity: '1',
    totalWithoutTax: '$ 59.31',
    productPrice: '19.77',
    shippingLabel: 'Free',
    productName: PRODUCTS.invicta,
    env: 'discountShippingOrder',
  },
  promotionProduct: {
    prefix: 'promotionProduct',
    postalCode: '33180',
    totalAmount: '$ 37.21',
    tax: '$ 2.44',
    subTotal: '$ 39.54',
    discount: '$ -19.77',
    productName: PRODUCTS.invicta,
    productQuantity: '2',
    productPrice: '19.77',
    env: 'promotionProductEnv',
  },
  // TODO: shashi will update as per sandbox env
  externalSeller: {
    prefix: 'externalSeller',
    postalCode: '33180',
    product1Name: PRODUCTS.coconut,
    product2Name: PRODUCTS.tshirt,
    totalAmount: '$ 1,266.88',
    tax: '$ 82.88',
    directSaleAmount: '$ 1,160.95',
    directSaleTax: '$ 75.95',
    directSaleEnv: 'directSale',
    externalSellerAmount: '$ 105.93',
    externalSellerTax: '$ 6.93',
    externalSaleEnv: 'externalSale',
    subTotal: '$ 1,174.00',
    productQuantity: '2',
    product1Price: '540.00',
  },
  requestRefund: {
    // orderId variable name for getFullRefundTotal
    fullRefundEnv: 'order1',
    // orderId variable name for getPartialRefund
    partialRefundEnv: 'order2',
    getFullRefundTotal: 108500,
    getPartialRefundTotal: 108500,
    subTotal: '$ 1,080.00',
  },
}
