name: '[QE] Cypress Runner'

on:
  schedule:
    # 7:00 AM UTC = 3:00 AM EDT
    - cron: '0 7 * * *'
  pull_request:
    branches:
      - master
      - main
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    paths-ignore:
      - CHANGELOG.md
      - docs/**

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  cypress:
    runs-on: macos-10.15
    # To avoid waste Cypress tests,
    # lets run it only when the pull request is ready.
    if: github.event.pull_request.draft == false
    steps:
      - name: Checkout CyberSource
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get cy-runner
        run: 'git clone https://github.com/vtex-apps/cy-runner.git'

      - name: Cache
        uses: actions/cache@v2
        with:
          path: '~/.cache/'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install Cypress
        run: |
          rm -rf .git
          yarn install --frozen-lockfile
        working-directory: ./cy-runner

      - name: Install Cybersource packages
        run: yarn install --frozen-lockfile

      - name: Cypress Runner
        run: yarn cy-r
        env:
          VTEX_QE: ${{ secrets.VTEX_QE }}
          NODE_NO_WARNINGS: 1
# Quota exceed, disabling to avoid false positve errors
#       - name: Save results
#         uses: actions/upload-artifact@master
#         if: always()
#         with:
#           name: cy-runner-logs
#           path: cy-runner/logs
