name: '[PSH] Quality Engineering'

on:
  push:
    branches: 
      - test/action-improvements

jobs:
  quality-engineering:
    name: QE
    uses: vtex-apps/usqa/.github/workflows/quality-engineering.yml@v1.0.0
    with:
      dotnetLint: true
      dotnetVersion: 3.0
      dotnetSonar: true
      dotnetSonarProjectKey: vtex-apps_cybersource
      dotnetSonarOrganization: vtex-apps
    secrets:
      githubToken: ${{ secrets.GITHUB_TOKEN }}
      sonarToken: ${{ secrets.SONAR_TOKEN }}
