name: '[PSH] Quality Engineering'

on:
  push:
    branches: 
      - main
      - master

jobs:
  quality-engineering:
    name: QE
    uses: vtex-apps/usqa/.github/workflows/quality-engineering.yml@v1.0.0
    with:
      dotnetLint: false
      dotnetVersion: 3.1
      dotnetSonar: true
      dotnetSonarProjectKey: vtex-apps_cybersource
      dotnetSonarOrganization: vtex-apps
      cypress: false
    secrets:
      githubToken: ${{ secrets.GITHUB_TOKEN }}
      sonarToken: ${{ secrets.SONAR_TOKEN }}
      cypressJson: ${{ secrets.VTEX_QE }}
